### ISSUE TITLE
have feature extraction as part of the model and not in the main script

### ISSUE THREAD

**Issue by KatGarmash** [cqfn/aibolit#574]
Why?

- it's intuitive to have feature extraction and computation to be close to model definition and training. Since the feature set is in fact part of the model

- when one loads an old pretrained model with its own set of features, the pipeline should be able to recognize that recommendation should be done with that old set of features. Right now it just uses the feature set defined in config.py

**Comment by lyriccoder** [comment]
1) As I remember @acheshkov  asked to have it outside of the model. Since we can count patterns not only for a model, but for different experiments, it was asked to keep it outside. Moreover, feature extraction doesn't have any state, it will be static method. So, again it is not related to a model

2)need to discuss. Config is a place where we keep current state of the aibolit. Lots of patterns can have errors. Thus, if we use config of a model, current implementation can be wrong

**Comment by KatGarmash** [comment]
1. the state is the set of features used at training the model. you could implement feature extraction as a separate class and have it as an attribute of a model, and u could also use it outside of the model.

2. yeah, but if you can't use the config of the model, then you can't use the model.

**Comment by KatGarmash** [comment]
1. plus, if in the future we do feature preprocessing such as standard scaling, we need to record the parameters of sclaing in the model.

**Comment by acheshkov** [comment]
@KatGarmash  there is issue #556 where you can suggest how it should work from an end-user point of view.

**Comment by KatGarmash** [comment]
> @KatGarmash there is issue #556 where you can suggest how it should work from an end-user point of view.

@acheshkov  i will, thanks
